### ISSUE TITLE
Zendesk tagging is not appearing in reports

### ISSUE THREAD

**Issue by SaraC19** [nickcolley/govuk-design-system-support#25]
## What
Zendesk tagging data is not pulling into the monthly reports that are pulled by the devs. Ideally I'd get both the primary tag and also the secondary one coming through, but I assume this needs the script to be adjusted slightly. I'm not sure if this helps, but I can ask the Zendesk support desk if there's a specific thing we need to include in the script to get this. 

## Why
So we can pull data on Zendesk tags for the Support Dashboard. 

## Who needs to work on this
Dev

## Who needs to review this
PA
## Done when

- [ ] The Zendesk tags (primary and secondary) are pulling into the reports that the developers pull.

**Comment by lfdebrux** [comment]
Thanks for flagging this @SaraC19. Just to clarify, this was working before right?

**Comment by lfdebrux** [comment]
Culprit appears to be this line:

https://github.com/alphagov/design-system-support/blob/0b2c0462c7e696b948f3c0ed21200b26a7d7614c/src/zendesk/getTicketsWithTags.js#L42

We're filtering out tags that don't start with `design-system`, however our tags now (?) start with `ds`.

**Comment by SaraC19** [comment]
Looks good now - thank you @lfdebrux !

**Comment by lfdebrux** [comment]
@SaraC19 great :D

With a small fix I am able to generate the CSV correctly locally. PR #26 includes the fix, this ticket can be closed once that has been reviewed and merged!
