### ISSUE TITLE
`createdMonthsAgo` flag doesn't work

### ISSUE THREAD

**Issue by hannalaakso** [nickcolley/govuk-design-system-support#6]
The flag that's reported in the README doesn't have any effect
```
npm run build:csv:github -- --createdMonthsAgo=3
```
As a temporary measure you can override the default here: https://github.com/alphagov/design-system-support/blob/master/src/github/index.js#L36

**Comment by vanitabarrett** [comment]
This seemed to be working for me the last time I tried it. Have asked @hannalaakso to double check.

**Comment by hannalaakso** [comment]
Yes, this seems to be working [as documented](https://github.com/alphagov/design-system-support#github) 👍  Possibly I was looking at the [Build all command](https://github.com/alphagov/design-system-support#build-all) which is when you can't pass the flag (but the docs reflect this so that's fine).
